### ISSUE TITLE
Documentation: are the tests representative of the real functioning of Prosody?

### ISSUE THREAD

**Issue by just1not2** [jitsi/jxs#20]
In order to test the Prosody component of a Jitsi infrastructure on Kubernetes, we tried using JXS. However, we did not find any documentation about how the software works and how the tests match the real functioning of Prosody.

The whole recap of our test is contained here: https://github.com/openfun/jitsi-k8s/blob/prosody-doc/docs/prosody/TEST.md

Our 2 main problems:
* we did not succeed in adding `jicofo` to the rooms we created (the documentation do not state clearly which domain should be set for `focus`, and we tried every combination: `[meet.example.com]`, `focus.[meet.example.com]`, `focus@[meet.example.com]`, ...)
* Between 400 and 500 added participants, we got a lot of `errors 500`, and the following logs were present on the Prosody server:
```
focus.[meet.example.com]:client_proxy                                         debug	received stanza from c2s session
focus.[meet.example.com]:client_proxy                                         debug	stanza to target: name = iq, type = error
sessionmanager                                                                debug	All resources of bq298_rxt0fimwqe are now offline
stanzarouter                                                                  debug	Could not route stanza to remote
c2s557148c1cde0                                                               debug	mod_smacks hibernation timeout reached...
c2s557148c1cde0                                                               debug	Destroying session for hibernating too long
c2s557148c1cde0                                                               debug	Destroying session for zu51vily3ayv8vv8@[meet.example.com]/f_ioZwdB (zu51vily3ayv8vv8@[meet.example.com])
```

We collected a good number of metrics on our Prosody pod (available [here](https://github.com/openfun/jitsi-k8s/blob/prosody-doc/docs/prosody/TEST.md)) but none of them show some problems on Prosody.

Given the results of our test, we think that some documentation on the following questions would benefit everyone using this repository:
* What does the tests exactly do? Are the tests representative of the normal functioning of Prosody?
* Does this cause any problem not to have Jicofo added to the rooms (the script does not crash)?
* Is the `error 500` representative of a real problem that our Prosody have (500 participants is max?) or is it a problem that is caused by JXS (too short delay between connections?)

**Comment by damencho** [comment]
> * What does the tests exactly do? Are the tests representative of the normal functioning of Prosody?

This is if you want to create high number of connections or high number of stanzas to pass through the server.



> * Does this cause any problem not to have Jicofo added to the rooms (the script does not crash)?

The script sends some messages to jicofo ... to emulate a call setup.



> * Is the `error 500` representative of a real problem that our Prosody have (500 participants is max?) or is it a problem that is caused by JXS (too short delay between connections?)

500 is a server error ... that is definitely error coming from the server.

**Comment by bgrozev** [comment]
I'll close this for now. We can certainly use better documentation, but this is meant mainly as a very specific tool for performance testing where knowledge of the details for the jitsi-meet system are already a prerequisite, so adding docs is not high on the priority list. Contributions are welcome and I'm happy to answer questions though!
